### PR TITLE
add benchmark; use more efficient UnmarshalText call

### PR DESCRIPTION
**Pull request by rogpeppe**
Initial results:

BenchmarkUnmarshal4Fields     300000          4399 ns/op         160 B/op          8 allocs/op

### CODE REVIEW

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by urosj** [comment]
Title wrong :) It's UnmarshallText ... btw, will we have to have UnmarshallText for every struct?

**Comment by urosj** [comment]
:+1:

**Comment by rogpeppe** [comment]
No, we only call UnmarshalText when there's an item in the struct
that implements TextUnmarshaler (in this case because we're using
a custom time unmarshaler)

**Pull request merged**
